#!/bin/bash

printf "### Removing old container\n"
docker kill youtube-comment-api
docker rm youtube-comment-api

printf "\n### Building Container...\n"
docker build -t youtube-comment-api .

printf "\n### Starting Container...\n"
docker run -d -p 49160:3000 -e "NODE_ENV=production" --restart=always --name youtube-comment-api youtube-comment-api

printf "\n\n### Result:\n"
docker ps --filter=[name=youtube-comment-api]
